ecomsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from shop import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('api/',include('shop.api.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/api/urls.py
from django.urls import path
from .api_view import (CategoryListApiView,
                       SmartphoneListAPIView,
                       LaptopListAPIView,
                       SmartphoneAPIDetailView,
                        CustomersListAPIView,


)

urlpatterns = [
    path('categories/', CategoryListApiView.as_view(), name='categories'),
    path('customers/', CustomersListAPIView.as_view(), name='customers'),
    path('smartphones/', SmartphoneListAPIView.as_view(), name='smartphones'),
    path('laptops/', LaptopListAPIView.as_view(), name='laptops'),
    path('smartphone/<int:id>/', SmartphoneAPIDetailView.as_view(), name='smartphone_detail'),

]

shop/urls.py
from django.urls import path
from shop import views

urlpatterns = [
    path('', views.BaseView.as_view(), name='home'),
    path('product/<str:ct_model>/<str:slug>/',views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/',views.CategoryDetailView.as_view(), name='category_detail'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/',views.AddCartView.as_view(),name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/',views.DeleteCartProductView.as_view(),name='remove_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/',views.ChangeQTYView.as_view(),name='qty'),
    path('checkout/',views.CheckoutView.as_view(),name='checkout'),
    path('new_order/',views.MakeOrderView.as_view(),name='new_order'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from sys import getsizeof
from django.urls import reverse
from django.utils import timezone


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__.meta.model.name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class MaxResolutionError(Exception):
    pass


class MinResolutionError(Exception):
    pass


class LatestProductsManager:

    @staticmethod
    def get_products_for_models(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_product = ct_model.model_class()._base_manager.all().order_by('-id')
            products.extend(model_product)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to),
                                  reverse=True)
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('laptop', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [dict(name=i.name, url=i.get_absolute_url(), count=getattr(i, f'{i.name}__count')) for i in qs]
        return data


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Category Name')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    min_resolution = (199, 199)
    max_resolution = (800, 800)
    max_image_size = 3145728

    class Meta:
        abstract = True

    slug = models.SlugField(unique=True, default=None)
    category = models.ForeignKey(Category, verbose_name='Product Category', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name='Product Name')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Product Price')
    discount_price = models.FloatField()
    description = models.TextField(verbose_name='Product Description', null=True)
    image = models.ImageField(verbose_name='Product Image')

    def __str__(self):
        return self.title

    # verify whether the image size is valid else raise error
    # def save(self, *args, **kwargs):
    #     image = self.image
    #     img = Image.open(image)
    #     min_width, min_height = self.min_resolution
    #     max_width, max_height = self.max_resolution
    #     if img.width < min_width or img.height < min_height:
    #         raise MinResolutionError("The image resolution is less than the minimum")
    #     if img.width > max_width or img.height > max_height:
    #         raise MaxResolutionError("The image resolution is more than the minimum")
    #     super().save(*args,**kwargs)
    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        new_img = img.convert('RGB')
        resized_img = new_img.resize((300, 300), Image.ANTIALIAS)
        filestream = BytesIO()
        resized_img.save(filestream, 'JPEG', quality=90)
        name = '{}.{}'.format(*self.image.name.split('.'))
        self.image = InMemoryUploadedFile(
            filestream, 'ImageField', name, 'jpeg/image', getsizeof(filestream), None
        )
        super().save(*args, **kwargs)


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Customer', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Total Price')

    def __str__(self):
        return f'Product: {self.content_object.title}'

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey('Customer', null=True, verbose_name='Customer', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_product = models.PositiveIntegerField(null=True)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='Total Price')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.owner} cart '




class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name='Customer', on_delete=models.CASCADE)
    phone = models.CharField(max_length=255, null=True, blank=True, verbose_name='Phone number')
    address = models.CharField(max_length=250, null=True, blank=True, verbose_name='Customer Address')
    orders = models.ManyToManyField('Order' ,max_length=255,blank=True,related_name='related_customer')
    def __str__(self):
        return f'Customer: {self.user.username} '


class Laptop(Product):
    diagonal = models.CharField(max_length=255)
    display = models.CharField(max_length=255)
    processor_freq = models.CharField(max_length=255)
    ram = models.CharField(max_length=255)
    video_card = models.CharField(max_length=255)
    time_without_charge = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.category.name} {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

    def get_model_name(self):
        return self.__class__._meta.model_name


class SmartPhone(Product):
    diagonal = models.CharField(max_length=255)
    display = models.CharField(max_length=255)
    resolution = models.CharField(max_length=255)
    ram = models.CharField(max_length=255)
    accum_volume = models.CharField(max_length=255)
    time_without_charge = models.CharField(max_length=255)
    sd = models.BooleanField(default=True)
    sd_volume_max = models.CharField(max_length=255, null=True, blank=True, verbose_name='Maximum internal memory')
    main_camera_mp = models.CharField(max_length=255)
    frontal_camera_mp = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.category.name} {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

    def get_model_name(self):
        return self.__class__._meta.model_name


class Order(models.Model):
    STATUS_NEW = 'NEW'
    STATUS_TM_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'pickup'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = {
        (STATUS_COMPLETED, 'new order'),
        (STATUS_TM_PROGRESS,'order in progress'),
        (STATUS_READY,'order is ready'),
        (STATUS_COMPLETED, 'order is completed')
    }

    BUYING_TYPE_CHOICES = {
        (BUYING_TYPE_DELIVERY,'delivery'),
        (BUYING_TYPE_SELF, 'pickup')
    }
    customer = models.ForeignKey(Customer,related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=28)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE,null=True,blank=True)
    address = models.CharField(max_length=2535,null=True,blank=True)
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default=STATUS_NEW)
    buying_type = models.CharField(max_length=255,choices=BUYING_TYPE_CHOICES, default=BUYING_TYPE_SELF)
    comment = models.TextField(null=True,blank=True)
    created_date = models.DateTimeField(auto_now=True)
    order_date = models.DateField(verbose_name='Order received date',default=timezone.now)


    def __str__(self):
        return str(self.id)

shop/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args,**kwargs)
        self.fields['order_date'].label = 'Order received date'
    order_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = Order
        fields = ['customer', 'first_name', 'last_name', 'phone', 'address', 'status', 'buying_type', 'comment',
                  'order_date']

shop/templates/shop/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script >
(function($) {
    $('#id_sd').on('click',function(){
    if(
    $('#id_sd').prop('checked') == true){
    $('#id_sd_volume_max').prop('readonly',false)
    $('#id_sd_volume_max').val('')
    $('#id_sd_volume_max').css('background','white')
    }else{
    $('#id_sd_volume_max').prop('readonly',true)
    $('#id_sd_volume_max').val('')
    $('#id_sd_volume_max').css('background','lightgray')}
})
})(django.jQuery);
</script>
{% endblock %}

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'home' %}">Shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">All Products</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                        <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <a href="{% url 'cart' %}" class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Cart
                    <span class="badge bg-dark text-white ms-1 rounded-pill">{{cart.products.count}}</span>
                </a>
            </form>
        </div>
    </div>
</nav>

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Shop in style</h1>
            <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
        </div>
    </div>
</header>


<div class="container">
<div class="row">
    <div class="col-lg-3">
        <h1 class="my-4">Category</h1>
        <div class="list-goup">
            {% for category in categories %}

            <a href="{{category.url}}" class="list-group-item">{{category.name}} ({{category.count}})</a>
            {% endfor %}

        </div>
    </div>
</div>

</div>
<!-- Section-->
<section class="py-5">
    {% block content%}
    <ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>{{message}}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
    {% endfor %}
</ul>
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

        {% for product in products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{product.image.url}}" alt="..."/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder"><a href="{% url 'product_detail' ct_model=product.get_model_name slug=product.slug %}">{{product.title}}</a></h5>
                            <!-- Product price-->
                            {{product.price}}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a  href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}"><button class="btn btn-danger">Add</button></a></div>
                    </div>
                </div>
            </div>
        {% endfor %}


        </div>
    </div>
    {% endblock %}
</section>

<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
</body>
</html>

shop/templates/shop/cart.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>Cart</h1>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>{{message}}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
    {% endfor %}
</ul>
{% endif %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Products Name</th>
      <th scope="col">Image</th>
      <th scope="col">Price</th>
      <th scope="col">Total Products</th>
      <th scope="col">Final Price</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart.products.all %}
    <tr>
      <th scope="row">{{ item.content_object.title }}</th>
      <td class="w-25"><img src="{{item.content_object.image.url}}" class="img-fluid"></td>
      <td>{{item.content_object.price}} $</td>
      <td>
        <form action="{% url 'qty' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}" method="POST">
          {% csrf_token %}
          <input type="number" value="{{item.qty}}" min="1" class="form-control" style="width:50px;" name="qty">
          <input type="submit"  class="btn btn-primary" style="width:50px;" value="qty">
        </form>
      </td>

      <td>{{item.final_price}} $</td>
      <td><a class="btn btn-danger" href="{% url 'remove_from_cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}">Delete</a></td>
    </tr>
{% endfor %}

    <tr>
      <th scope="row"><strong>Total</strong></th>
      <td><strong>Items:   {{cart.total_product}}</strong></td>
      <td><strong>Sum:   {{cart.final_price}} $</strong></td>
      <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Check it out</button></a></td>
    </tr>

  </tbody>
</table>
{% endblock %}

shop/templates/shop/category_detail.html
{% extends 'shop/base.html' %}
{% load specifications %}
{% block content %}
<h1>{{category.name}}</h1>
 <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
 {% for product in products_f %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" style="width:400px;height:400px;" src="{{product.image.url}}" alt="..."/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder"><a href="{% url 'product_detail' ct_model=product.get_model_name slug=product.slug %}">{{product.title}}</a></h5>
                            <!-- Product price-->
                            {{product.price}}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a  href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}"><button class="btn btn-danger">Add to Cart</button></a></div>
                    </div>
                </div>
            </div>
        {% endfor %}
 </div>
{% endblock %}

shop/templates/shop/checkout.html
{% extends 'shop/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<h1>Check it out</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Products Name</th>
      <th scope="col">Image</th>
      <th scope="col">Price</th>
      <th scope="col">Total Products</th>
      <th scope="col">Final Price</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart.products.all %}
    <tr>
      <th scope="row">{{ item.content_object.title }}</th>
      <td class="w-25"><img src="{{item.content_object.image.url}}" class="img-fluid"></td>
      <td>{{item.content_object.price}} $</td>
      <td>
       {{ item.qty }}
      </td>
      <td>{{item.final_price}} $</td>
    </tr>
{% endfor %}

    <tr>
      <th scope="row"><strong>Total</strong></th>
      <td><strong>Items:   {{cart.total_product}}</strong></td>
      <td><strong>Sum:   {{cart.final_price}} $</strong></td>
    </tr>

  </tbody>
</table>

<hr>
<h1> Order Form</h1>
<form action="{% url 'new_order' %}" method="POST">
  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" class="btn btn-success btn-block mb-3" value="Check">
</form>



{% endblock %}

shop/templates/shop/laptop_specification.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<table class="table">
  <tbody>
    <tr>
      <td>diagonal</td>
      <td>{{product.diagonal}}</td>
    </tr>
      <tr>
      <td>display</td>
      <td>{{product.display}}</td>
    </tr>
      <tr>
      <td>processor_freq</td>
      <td>{{product.processor_freq}}</td>
    </tr>
      <tr>
      <td>ram</td>
      <td>{{product.ram}}</td>
    </tr>
      <tr>
      <td>video_card</td>
      <td>{{product.video_card}}</td>
    </tr>
      <tr>
      <td>time_without_charge</td>
      <td>{{product.time_without_charge}}</td>
    </tr>
  </tbody>
</table>
</body>
</html>

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% load specifications %}
{% block content %}
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="#">{{product.category.name}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{product.title}}</li>
  </ol>
</nav>
<div class="row">

    <div class="col-md-4">
        <img src="{{product.image.url}} " class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>{{product.title}}</h3>
        <p>Price: {{product.price}}</p>
        <p>Description: {{product.description}}</p>
            <hr>
    <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %}"><button class="btn btn-danger">Add to Cart</button></a>
    </div>

    <div >
        {{product|product_spec}}
<!--        {% if product.category.name == 'laptop' %}-->
<!--        {% include 'shop/laptop_specification.html' %}-->
<!--        {% endif %}-->
<!--        {% if product.category.name == 'smartphone' %}-->
<!--        {% include 'shop/smarphone_specification.html' %}-->
<!--        {% endif %}-->

    </div>


</div>
{% endblock %}

shop/templates/shop/smarphone_specification.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<table class="table">
  <tbody>
    <tr>
      <td>diagonal</td>
      <td>{{product.diagonal}}</td>
    </tr>
      <tr>
      <td>display</td>
      <td>{{product.display}}</td>
    </tr>
      <tr>
      <td>resolution</td>
      <td>{{product.resolution}}</td>
    </tr>
      <tr>
      <td>ram</td>
      <td>{{product.ram}}</td>
    </tr>
      <tr>
      <td>accum_volume</td>
      <td>{{product.accum_volume}}</td>
    </tr>
      <tr>
      <td>time_without_charge</td>
      <td>{{product.time_without_charge}}</td>
    </tr>
    {% if product.sd %}
    <tr>

      <td>sd</td>
      <td>{{product.sd}}</td>
    </tr>
  <tr>
      <td>sd_volume_max</td>
      <td>{{product.sd_volume_max}}</td>
    </tr>
    {% endif %}
  <tr>
      <td>main_camera_mp</td>
      <td>{{product.main_camera_mp}}</td>
    </tr>
  <tr>
      <td>frontal_camera_mp</td>
      <td>{{product.frontal_camera_mp}}</td>
    </tr>
  </tbody>
</table>
</body>
</html>